### ISSUE TITLE
no such table: my_app_search

### ISSUE THREAD

**Issue by imv7** [CleverProgrammer/codedaddies_list#1]
Request Method: | POST
-- | --
http://127.0.0.1:8000/new_search
2.2.4
OperationalError
no such table: my_app_search
C:\Users\IgorMonteiroVieira\AppData\Local\Programs\Python\Python37\lib\site-packages\django\db\backends\sqlite3\base.py  in execute, line 383
C:\Users\IgorMonteiroVieira\AppData\Local\Programs\Python\Python37\python.exe

**Comment by thestorme212** [comment]
try in terminal :
 python manage.py makemigrations
 python manage.py migrate

**Comment by oyedejioyewole** [comment]
**Try making migrations for the django project then trying it again**
